
export enum FamilyCodePACopacker{
    COPACKER="24-PRODUTO ACABADO COPACKER"
};

export enum GroupCodePACopacker{
    REFRIGERANTE_TONICA="0001-REFRIGERANTE/ TONICA",
    ENERGETICOS="0002-ENERGETICOS (BOMBADÃO)",
    COQUETEIS="0003-COQUETEIS",
    CERVEJA="0004-CERVEJA",
    AGUA="0005-AGUA",
    ALCOOL="0006-ALCOOL",
    SUCO_REFRESCO="0007-SUCO/ REFRESCO/ AGUA DE COCO",
    VINHO="0008-VINHO",
    ESPUMANTE="0009-ESPUMANTE",
    WHISKY="0010-WHISKY",
    CACHACA_PINGA_AGUARDENTE="0011-CACHACA/ PINGA/ AGUARDENTE",
    VODKA="0012-VODKA",
    GIN="0013-GIN",
    SAQUE="0014-SAQUE",
    TEQUILA="0015-TEQUILA",
    CONHAQUE="0016-CONHAQUE",
    CHOPP="0017-CHOPP",
    RUM="0018-RUM"
};

export enum TypeCodeoPACopacker{
    PRODUTO_ACABADO="04-PA-PRODUTO ACABADO", 
    SERVICO_INDUSTRIALIZADO="04-SI-SERVICO INDUSTRIALIZACAO VENDA"
};

