
export enum FamilyCodeInsumos{
    INSUMOS_PROPRIOS="27 - INSUMOS PRODUTIVOS PROPRIOS", 
    INSUMOS_IND="28 - INSUMOS PRODUTIVOS IND",
    INSUMOS_COPACKER="29 - INSUMOS PRODUTIVOS COPACKER",
    INSUMOS_NAO_PRODUTIVOS="30 - INSUMOS NAO PRODUTIVOS",
};

export enum GroupCodeInsumos{
    INSUMOS="0100 - INSUMOS",
    ROTULOS="0101 - ROTULOS",
    PREFORMAS="0102 - PREFORMAS", 
    TAMPAS="0103 - TAMPAS (PET/ METALICA/ ABRE FACIL)",
    FILMES="0104 - FILMES",
    AROMAS_CONCENTRADOS_EMULSOES_KITS="0105 - AROMAS/ CONCENTRADOS/ EMULSOES/ KITS", 
    CORANTES="0106 - CORANTES", 
    EDULCORANTES="0107 - EDULCORANTES",
    ACUCAR="0108 - ACUCAR",
    ACIDULANTE="0109 - ACIDULANTE/ REGULADOR DE ACIDEZ/ ANTIOXIDANTE", 
    CONSERVANTES="0110 - CONSERVANTES", 
    GASES="0111 - GASES", 
    VITAMINAS_ENERGIZANTES="0112 - VITAMINAS/ ENERGIZANTES", 
    SUCOS_EXTRATOS="0113 - SUCOS/ EXTRATOS", 
    CONJUNTO_LATAS_TAMPA="0114 - CONJUNTO LATAS/ TAMPA",
    VASILHAMES="0115 - VASILHAMES (VIDRO)", 
    CAIXAS="0116 - CAIXAS", 
    AGUARDENTE_ETANOL_SAQUE_VINHO="0117 - AGUARDENTE/ ETANOL/ SAQUE/ VINHO", 
    COPO_ENVASE="0118 - COPO PARA ENVASE", 
    MALTE_MALTOSE="0119 - MALTE/ MALTOSE",
    LUPULOS="0120 - LUPULOS", 
    ESTABILIZANTES_ENZIMAS="0121 - ESTABILIZANTES/ ENZIMAS",
    FERMENTO="0122 - FERMENTO",
    SAIS="0125 - SAIS", 
    CANTONEIRA_BAGS="0124 - CANTONEIRA/ SEPARADOR DE CAMADAS/ BAGS",
    LACRE="0126 - LACRE",
    ETIQUETAS="0127 - ETIQUETAS",
    INSUMOS_NAO_PRODUTIVOS = "0200 - INSUMOS NAO PRODUTIVOS",
    HIGIENIZACAO ="0201 - HIGIENIZACAO",
    MEIOS_FILTRANTES="0202 - MEIOS FILTRANTES",
    COLAS_ADESIVOS="0203 - COLAS/ ADESIVOS",
    ETIQUETAS_RIBBON="0204 - ETIQUETAS/ RIBBON",
    LENHA="0205 - LENHA",
    DATADORA="0206 - DATADORA",
};

export enum TypeCodeoInsumos{
    MATERIA_PRIMA="01-MP-MATERIA PRIMA",
    MATERIA_PRIMA_TERCEIROS="01-MT-MATERIA PRIMA TERCEIROS",
    EMBALAGEM="02-EM-EMBALAGEM",
    EMBALAGEM_TERCEIROS="02-ET-EMBALAGEM TERCEIROS",
    PRODUTO_PROCESSO="03-PP-PRODUTO EM PROCESSO"
};

