export enum FamilyCodeIndirectProducts {
    INSUMOS_NAO_PRODUTIVOS="30 - INSUMOS NAO PRODUTIVOS",
    MATERIAL_CONSUMO="31 - MATERIAL DE CONSUMO",
    PRODUTO_MANUTENCAO_INDUSTRIAL="32 - PRODUTOS MANUTENCAO INDUSTRIAL",
    PRODUTO_MANUTENCAO_FROTAS="33 - PRODUTOS MANUTENCAO DE FROTAS",
    SUBPRODUTO="36 - SUBPRODUTO",
    IMOBILIZADO="37 - IMOBILIZADO",
    MERCADORIA_REVENDA="39 - MERCADORIA DE REVENDA"
};

// ---Grupos de Produtos Indiretos---

export enum GroupCodeIndirectProducts_30{
    INSUMOS_NAO_PRODUTIVOS = "0200 - INSUMOS NAO PRODUTIVOS",
    HIGIENIZACAO ="0201 - HIGIENIZACAO",
    MEIOS_FILTRANTES="0202 - MEIOS FILTRANTES",
    COLAS_ADESIVOS="0203 - COLAS/ ADESIVOS",
    ETIQUETAS_RIBBON="0204 - ETIQUETAS/ RIBBON",
    LENHA="0205 - LENHA",
    DATADORA="0206 - DATADORA",
    MATERIAL_CONSUMO="0300 - MATERIAL DE CONSUMO",
};

export enum GroupCodeIndirectProducts_31{
    VASILHAMES="0115 - VASILHAMES (VIDRO)",
    CAIXAS="0116 - CAIXAS",
    CANTONEIRA_SEPARADOR_CAMADAS="0124 - CANTONEIRA/ SEPARADOR DE CAMADAS/ BAGS",
    ETIQUETAS="0127 - ETIQUETAS",
    INSUMOS_NAO_PRODUTIVOS = "0200 - INSUMOS NAO PRODUTIVOS",
    HIGIENIZACAO ="0201 - HIGIENIZACAO",
    MEIOS_FILTRANTES="0202 - MEIOS FILTRANTES",
    COLAS_ADESIVOS="0203 - COLAS/ ADESIVOS",
    ETIQUETAS_RIBBON="0204 - ETIQUETAS/ RIBBON",
    LENHA="0205 - LENHA",
    DATADORA="0206 - DATADORA",
    MATERIAL_CONSUMO="0300 - MATERIAL DE CONSUMO",
    FARMACIA="0301 - FARMACIA",
    MATERIAL_LABORATORIO="0302 - MATERIAL DE LABORATORIO",
    INFORMATICA="0303 - INFORMATICA",
    MERCADO="0304 - MERCADO",
    COMBUSTIVEL="0305 - COMBUSTIVEL",
    MATERIAL_ESCRITORIO="0306 - MATERIAL DE ESCRITORIO",
    MATERIAL_CONSTRUCAO="0307 - MATERIAL DE CONSTRUCAO",
    UNIFORMES_EPIS="0308 - UNIFORMES E EPIS",
    BENEFICIOS_PRODUTOS="0309 - BENEFICIOS PRODUTOS",
    PECAS_FROTAS="0310 - PECAS FROTAS",
    PECAS_INDUSTRIA_LABORATORIO ="0311 - PECAS INDUSTRIA/ LABORATORIO", 
    ATIVOS_GIRO="0312 - ATIVOS GIRO",
    BRINDES="0313 - BRINDES", 
    RESIDUOS_RECICLAVEIS="0314 - RESIDUOS RECICLAVEIS", 
    LANCHES_REFEICOES="0316 - LANCHES E REFEICOES",
    ENERGIA="0317 - ENERGIA",
    MATERIAL_MARKETING="0318 - MATERIAL MARKETING",
    CLICHE="0319 - CLICHE",
    ELETROPORTATES="0320 - ELETROPORTATES",
    MANUTENCAO_PREDIAL="0321 - MANUTENCAO PREDIAL",
    MOVEIS_UTENSILIOS="0506 - MOVEIS E UTENSILIOS"
};

export enum GroupCodeIndirectProducts_32{
    MATERIAL_CONSUMO="0300 - MATERIAL DE CONSUMO",
    FARMACIA="0301 - FARMACIA",
    MATERIAL_LABORATORIO="0302 - MATERIAL DE LABORATORIO",
    INFORMATICA="0303 - INFORMATICA",
    MERCADO="0304 - MERCADO",
    COMBUSTIVEL="0305 - COMBUSTIVEL",
    MATERIAL_ESCRITORIO="0306 - MATERIAL DE ESCRITORIO",
    MATERIAL_CONSTRUCAO="0307 - MATERIAL DE CONSTRUCAO",
    UNIFORMES_EPIS="0308 - UNIFORMES E EPIS",
    BENEFICIOS_PRODUTOS="0309 - BENEFICIOS PRODUTOS",
    PECAS_FROTAS="0310 - PECAS FROTAS",
    PECAS_INDUSTRIA_LABORATORIO ="0311 - PECAS INDUSTRIA/ LABORATORIO", 
    ATIVOS_GIRO="0312 - ATIVOS GIRO",
    BRINDES="0313 - BRINDES", 
    RESIDUOS_RECICLAVEIS="0314 - RESIDUOS RECICLAVEIS", 
    LANCHES_REFEICOES="0316 - LANCHES E REFEICOES",
    ENERGIA="0317 - ENERGIA",
    MATERIAL_MARKETING="0318 - MATERIAL MARKETING",
    CLICHE="0319 - CLICHE",
    ELETROPORTATES="0320 - ELETROPORTATES",
    MANUTENCAO_PREDIAL="0321 - MANUTENCAO PREDIAL",
};

export enum GroupCodeIndirectProducts_33{
    PECAS_FROTAS="0310 - PECAS FROTAS",
};

export enum GroupCodeIndirectProducts_36{
    RESIDUOS_RECICLAVEIS="0314 - RESIDUOS RECICLAVEIS", 
    SUBPRODUTOS="0600 - SUBPRODUTOS"
};

export enum GroupCodeIndirectProducts_37{
    VASILHAMES="0115 - VASILHAMES (VIDRO)",
    CAIXAS="0116 - CAIXAS",
    MATERIAL_MARKETING="0318 - MATERIAL MARKETING",
    ATIVOS_IMOBILIZADOS="0500 - ATIVOS IMOBILIZADOS",
    MAQUINAS_EQUIPAMENTOS="0501 - MAQUINAS E EQUIPAMENTOS",
    GELADEIRA="0502 - GELADEIRA",
    VEICULO="0503 - VEICULO",
    TERRENO="0504 - TERRENO",
    EDIFICACOES_BENFEITORIAS="0505 - EDIFICACOES E BENFEITORIAS",
    MOVEIS_UTENSILIOS="0506 - MOVEIS E UTENSILIOS",
    COMPUTADORES_PERIFERICOS="0507 - COMPUTADORES E PERIFERICOS",
    FERRAMENTAS_ACESSORIOS="0508 - FERRAMENTAS E ACESSORIOS"
};

export enum GroupCodeIndirectProducts_39{
    ATIVOS_IMOBILIZADOS="0500 - ATIVOS IMOBILIZADOS",
    MAQUINAS_EQUIPAMENTOS="0501 - MAQUINAS E EQUIPAMENTOS",
    GELADEIRA="0502 - GELADEIRA",
    VEICULO="0503 - VEICULO",
    TERRENO="0504 - TERRENO",
    EDIFICACOES_BENFEITORIAS="0505 - EDIFICACOES E BENFEITORIAS",
    MOVEIS_UTENSILIOS="0506 - MOVEIS E UTENSILIOS",
    COMPUTADORES_PERIFERICOS="0507 - COMPUTADORES E PERIFERICOS",
    FERRAMENTAS_ACESSORIOS="0508 - FERRAMENTAS E ACESSORIOS"
};


// ---Tipo do Produtos Indiretos---
export enum TypeCodeIndirectProducts{
    MATERIAL_CONSUMO="07-MC-MATERIAL DE CONSUMO",
    ATIVO_IMOBILIZADO="08-AI-ATIVO IMOBILIZADO",
    SUBPRODUTO="05-SP-SUBPRODUTO",
    MERCADORIA="00-ME-MERCADORIA",
    PRODUTO_PROCESSO="06-PI-PRODUTO EM PROCESSO"
};



