
export enum FamilyCodeService{
    SERVICOS="34 - SERVIÇOS",
    IMOBILIZADO="37 - IMOBILIZADO",
};

export enum GroupCodeService{
    OUTROS="0401 - OUTROS SERVICOS",
    PROMOTORES="0402 - PROMOTORES",
    SOFTWARE="0403 - MANUTENCAO DE SOFTWARE",
    CONTABEIS="0404 - SERVICOS CONTABEIS",
    ADVOCATICIOS="0405 - SERVICOS ADVOCATICIOS",
    CONSULTORIA="0406 - CONSULTORIA",
    SEGURANCA_PORTARIA="0407 - SEGURANCA E PORTARIA",
    INDUSTRIA="0408 - SERVICO INDUSTRIA",
    FRONTA="0409 - SERVICO FROTA",
    CORPORATIVO="0410 - CORPORATIVO",
    BENEFICIOS="0411 - BENEFICIOS SERVICOS",
    FRETES="0412 - FRETES - TMS"     
};

export enum TypeCodeService{
    IMOBILIZADO="08-AI-ATIVO IMOBILIZADO",
    SERVICO="09-SV-SERVIÇO",
};

