
export enum FamilyCodePAUnitary{
    PRODUTO_ACABADO="20-PRODUTO ACABADO",
    PA_CERVEJARIA="21-PRODUTO ACABADO IND - CERVEJARIA",
    PA_REFRIKO="22-PRODUTO ACABADO IND - REFRIKO",
    PA_MORAVIA="23-PRODUTO ACABADO IND - MORAVIA",
    PA_EXPORTACAO="25-PRODUTO ACABADO EXPORTAÇÃO",
    PA_REVENDA="26-PRODUTO ACABADO REVENDA",
    SERVICO_INDUSTRIALIZACAO="35-SERVIÇOS DE INDUSTRIALIZAÇÃO IND"
};

export enum GroupCodePAUnitary{
    REFRIGERANTE_TONICA="0001-REFRIGERANTE/ TONICA",
    ENERGETICOS="0002-ENERGETICOS (BOMBADÃO)",
    COQUETEIS="0003-COQUETEIS",
    CERVEJA="0004-CERVEJA",
    AGUA="0005-AGUA",
    ALCOOL="0006-ALCOOL",
    SUCO_REFRESCO="0007-SUCO/ REFRESCO/ AGUA DE COCO",
    VINHO="0008-VINHO",
    ESPUMANTE="0009-ESPUMANTE",
    WHISKY="0010-WHISKY",
    CACHACA_PINGA_AGUARDENTE="0011-CACHACA/ PINGA/ AGUARDENTE",
    VODKA="0012-VODKA",
    GIN="0013-GIN",
    SAQUE="0014-SAQUE",
    TEQUILA="0015-TEQUILA",
    CONHAQUE="0016-CONHAQUE",
    CHOPP="0017-CHOPP",
    RUM="0018-RUM"
};

export enum TypeCodeoPAUnitary{
    MERCADORIA="00-ME-MERCADORIA", 
    SERVICO_INDUSTRIALIZACAO_COMPRA = "01-SC-SERVICO INDUSTRIALIZAÇÃO COMPRA",
    SERVICO_INDUSTRIALIZADO="04-SI-SERVICO INDUSTRIALIZACAO VENDA",
    PRODUTO_ACABADO="04-PA-PRODUTO ACABADO",
};

